### PR TITLE
Add javascript

### PR DESCRIPTION
**Pull request by rebaz36**
- Speakers Object
- Add Dynamic components
- Generate Speakers through javascript
- toggle menu bar

### CODE REVIEW

**Review by tufoinnkuo10 — CHANGES_REQUESTED** [review]
Hi @rebaz36 

Great job so far. There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ design well followed
✅ project is as expected

Required Changes ♻️
Check the comments under the review
- [required] kindly add a video to your PR description/Readme presenting the features of the project. kindly ensure it contains a highlight about a piece of the code that you find interesting or proud of making.
- [required]please make use of GitHub Pages to deploy the web page and kindly ensure A link to the deployed project is present in the README. the live preview link in your readme seems to be broken please look into it.

tufoin

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.
- [ optional] you can set your nav links to take a user to the different page sections. this will ease navigation. great work 👍🏾 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by rebaz36** [comment]
Thanks @tufoinnkuo10 for the feedback i have Deployed the project and added the Video Demonstration and Live link to the README File

**Review by sumairq — APPROVED** [review]
## Hi  @rebaz36 , 



In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by rebaz36** [comment]
Thanks a lot @sumairq

**Pull request merged**
